### PR TITLE
added include readme + m2r2 for conversion

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
## Proposed changes

This PR refactores the docs by directly including the README.md file in the docs/source/index.rst file.

This greatly improves the code maintainability by reducing "code" duplication.

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [x] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Only "drawback" is it now shows all the badges in the README page of the docs (but maybe that's not too much of an issue?)
What do you think @Shimwell @billingsley-john ?

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
Failing tests related to #806

**Comment by shimwell** [comment]
Great suggestion, I really like it

**Comment by shimwell** [comment]
Looking at the [new docs](https://paramak--807.org.readthedocs.build/en/807/) that were built we have a few things to consider.

The readme contains a like to the documentation, so do this PR would mean the documentation contains a like to itself.
The readme has no list of contents with links
The readme.md is missing the YouTube video.

The readme has lots of duplication in but perhaps the way to solve this is to remove the duplication from the readme instead of mirroring the readme in the read the docs

Perhaps as these two things are different it is best just to reduce the readme to a bare minimum and have a big link to the documentation

**Comment by shimwell** [comment]
Also just to mention the readme is also copied here https://pypi.org/project/paramak/

**Comment by RemDelaporteMathurin** [comment]
> The readme contains a like to the documentation, so do this PR would mean the documentation contains a like to itself.

Yes. Doception

> The readme has no list of contents with links

The list of content still appears at the bottom of the page (we can make it appear before the readme).

> The readme.md is missing the YouTube video.

Yep but it has a link

> The readme has lots of duplication in but perhaps the way to solve this is to remove the duplication from the readme instead of mirroring the readme in the read the docs
>
> Perhaps as these two things are different it is best just to reduce the readme to a bare minimum and have a big link to the documentation

As you like, it was just an idea to reduce the amount of maintainance when changes are made in the doc 😃

**Comment by shimwell** [comment]
Perhaps #814 is another option

**Comment by RemDelaporteMathurin** [comment]
> Perhaps #814 is another option

I think that one is better. CLosing this :-)

**Pull request closed without merging**
