### PR TITLE
New component: Vacuum Vessel with ports

### PR DESCRIPTION
**Pull request by RemiTheWarrior**
## Proposed changes

This PR solves #339 and adds a new parametric component VacuumVessel.
The vacuum vessel is cylindrical and holes for portplugs can be made in it.

The ports section can be circular or rectangular. Rectangular ports can be filleted by specifying a fillet radius. The rotated ports from #337 can also be added.

Usage:
```python
import paramak


vessel = paramak.VacuumVessel(
    height=2, inner_radius=1, thickness=0.2,
    )

vessel.export_stp('vessel.stp')

```

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [x] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

This PR also adds a new attribute to ExtrudeCircleShape and ExtrudeStraightShape that makes the extrusion in both directions optional. Defaults is True.

### CODE REVIEW

**Comment by Shimwell** [comment]
So far so good, I can make the model and have drawn a diagram for the docs

Screenshot from 2020-10-07 18-28-46

**Comment by Shimwell** [comment]
I think rotated_ports might need another argument for azimuthal_placement

**Comment by Shimwell** [comment]
I'm wondering if we should opt for a different approach where the circular ports and rectangular ports (with fillet option) should be added as parametric components. Then they can be used elsewhere (e.g when cutting the blanket as well). What do you think @RemiTheWarrior

**Comment by Shimwell** [comment]
Screenshot from 2020-10-07 18-51-10

**Comment by Shimwell** [comment]
I've pushed some documentation to the branch

**Comment by RemiTheWarrior** [comment]
@Shimwell I've added the azimuth_placement_angle for the rotated ports

**Comment by Shimwell** [comment]
> > I'm wondering if we should opt for a different approach where the circular ports and rectangular ports (with fillet option) should be added as parametric components. Then they can be used elsewhere (e.g when cutting the blanket as well). What do you think @RemiTheWarrior
> 
> I guess that would be the way to go if these shapes are needed elswhere. I don't know if it's useful to have these kinds of shapes (except for rotated ports) as seperated parametric components cause they are really primitive shapes. Right now these are stored in the .cut argument of the VV.
> 
> What do you think ?

I am not sure, I guess one of the advantages of having them as seperate shapes is that it is easier to make repeating ports. The MAST-U vessel appears to have repeating circular ports which could be done with an azimuthal placement

**Comment by RemiTheWarrior** [comment]
@Shimwell 

Better remove these cutting options from the vacuum vessel shape then. The cutting for the ports would be done like this:

```python

cutting_piece1 = paramak.ExtrudeCircleShape(......, azimuth_placement_angle=[0, 20, 30])
cutting_piece2 = paramak.ExtrudeStraightShape(......)

vessel = paramak.VacuumVessel(
    height=2, inner_radius=1, thickness=0.2,
   cut=[cutting_piece1, cutting_piece2],
    )

vessel.export_stp('vessel.stp')
```

Therefore there is no need of having the cutting_pieces made inside the VacuumVessel shape

**Comment by Shimwell** [comment]
> @Shimwell
> 
> Better remove these cutting options from the vacuum vessel shape then. The cutting for the ports would be done like this:
> 
> ```python
> cutting_piece1 = paramak.ExtrudeCircleShape(......, azimuth_placement_angle=[0, 20, 30])
> cutting_piece2 = paramak.ExtrudeStraightShape(......)
> 
> vessel = paramak.VacuumVessel(
>     height=2, inner_radius=1, thickness=0.2,
>    cut=[cutting_piece1, cutting_piece2],
>     )
> 
> vessel.export_stp('vessel.stp')
> ```
> 
> Therefore there is no need of having the cutting_pieces made inside the VacuumVessel shape

yes I think this is the way to go

**Comment by RemiTheWarrior** [comment]
Just putting the add_ports method here so that it isn't lost:
```python
    def add_ports(self):
        cutter_shapes = []
        safety_factor = 2
        # circular ports
        for port in self.circular_ports:
            port_z_pos, placement_angle, radius = port
            shape = ExtrudeCircleShape(
                points=[(0, port_z_pos)],
                distance=2*(self.inner_radius+self.thickness*safety_factor),
                radius=radius,
                azimuth_placement_angle=placement_angle - 90,
                extrude_both=False)
            cutter_shapes.append(shape)

        # rectangular ports
        for port in self.rectangular_ports:
            port_z_pos, placement_angle, port_width, port_height = port[:4]
            points = [
                (-port_width/2, -port_height/2),
                (port_width/2, -port_height/2),
                (port_width/2, port_height/2),
                (-port_width/2, port_height/2),
            ]
            points = [(e[0], e[1] + port_z_pos) for e in points]
            shape = ExtrudeStraightShape(
                points=points,
                distance=2*(self.inner_radius+self.thickness*safety_factor),
                azimuth_placement_angle=placement_angle - 90,
                extrude_both=False
                )

            # add fillet
            if len(port) == 5:
                shape.solid = shape.solid.edges('#Z').fillet(port[4])
            cutter_shapes.append(shape)

        # rotated ports
        for port in self.rotated_ports:
            center_point, polar_coverage_angle, polar_placement_angle, \
                rotation_angle, azimuth_placement_angle = port[:5]
            shape = PortCutterRotated(
                center_point=center_point,
                polar_coverage_angle=polar_coverage_angle,
                polar_placement_angle=polar_placement_angle,
                max_distance_from_center=2*(
                    self.inner_radius+self.thickness*safety_factor),
                rotation_angle=rotation_angle,
                azimuth_placement_angle=azimuth_placement_angle,
                )

            # add fillet
            if len(port) == 6:
                shape.solid = shape.solid.edges().fillet(port[5])
            cutter_shapes.append(shape)

        self.cut = cutter_shapes
```

**Comment by Shimwell** [comment]
@RemiTheWarrior is there any chance that extruded_spline_shape.py and extruded_mixed_shape.py could be updated to accept the both argument as well. Just to keep everything the same

**Comment by Shimwell** [comment]
actually that both direction thing is just the sort of thing that would make a great first commit issue. So I shall save it for a new contributor

**Pull request merged**
