### PR TITLE
export_3d_image removed

### LINKED ISSUE #148: BUG: export_3d_image method not working
In #138 we added some more tests in order to improve the code coverage but some are failing. In particular the one involving `export_3d_image` method.

See [this build](https://app.circleci.com/pipelines/github/ukaea/paramak/345/workflows/92ca15a7-67fe-4d0a-ae87-b12198ae0c01/jobs/352)

### PR DESCRIPTION
**Pull request by RemiTheWarrior**
This PR resolves #148 

Coverage : 95%.

### CODE REVIEW

**Comment by Shimwell** [comment]
I'm just going to get some export_stl working for the reactor before merging this.

Then we can still have this functionality as an example

**Comment by Shimwell** [comment]
Reactor.export_stl() is now in the code base so reproducing these rendering scripts as examples is now easier

**Comment by RemiTheWarrior** [comment]
@Shimwell any idea why the tests for export_3d_image() method now raise conflicts ? shall I still delete them ?

**Comment by Shimwell** [comment]
I'm having a quick go at fixing this using a headless rendering method
https://pyrender.readthedocs.io/en/latest/examples/offscreen.html

**Comment by Shimwell** [comment]
The headless rendering is still a bit tricky and I noticed it depends on the graphics card drivers as well. So removing the export_3d_image really does look like the easiest option.

I have finally made the render example and have that ready to merge in with PR #203

**Pull request merged**
