### PR TITLE
updated R1 variable ToroidalFieldCoilTripleArc

### PR DESCRIPTION
**Pull request by billingsley-john**
## Proposed changes

PR which updates the ToroidalFieldCoilTripleArc class so that the R1 variable is used correctly, as described in the documentation.

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by billingsley-john** [comment]
Resolves #785

**Comment by billingsley-john** [comment]
ToroidalFieldCoilPrincetonD has a similar issue; however, is documented correctly. How do you feel @Shimwell @RemDelaporteMathurin about this? I think both R1 values in both classes should correspond to the same distance, it is a question of whether it's the inner or outer distance?
One thing to note is that TFCoilPrincetonD also has R2, which is an 'inner' radius, perhaps, R1 should do the same, which would suggest updating the image for TfCoilTripleArc rather than the class.

**Comment by shimwell** [comment]
I have a slight preference for inner distance as I think it makes the radial build easier and allows us to keep the same diagram

**Comment by RemDelaporteMathurin** [comment]
> ToroidalFieldCoilPrincetonD has a similar issue; however, is documented correctly. How do you feel @Shimwell @RemDelaporteMathurin about this? I think both R1 values in both classes should correspond to the same distance, it is a question of whether it's the inner or outer distance?

I agree with @Shimwell , inner is best.

> One thing to note is that TFCoilPrincetonD also has R2, which is an 'inner' radius, perhaps, R1 should do the same, which would suggest updating the image for TfCoilTripleArc rather than the class.

I do agree that R1 should be a inner radius as it makes it easier - I think - to build with it.

**Comment by billingsley-john** [comment]
> > ToroidalFieldCoilPrincetonD has a similar issue; however, is documented correctly. How do you feel @Shimwell @RemDelaporteMathurin about this? I think both R1 values in both classes should correspond to the same distance, it is a question of whether it's the inner or outer distance?
> 
> I agree with @Shimwell , inner is best.
> 
> > One thing to note is that TFCoilPrincetonD also has R2, which is an 'inner' radius, perhaps, R1 should do the same, which would suggest updating the image for TfCoilTripleArc rather than the class.
> 
> I do agree that R1 should be a inner radius as it makes it easier - I think - to build with it.

I agree with you both - as in R1 as outlined in the documentation.

**Review by shimwell — APPROVED** [review]
I agree with you all as well :-)

**Pull request merged**
