### PR TITLE
Switching to elongation triangularity instead of plasma high point

### LINKED ISSUE #338: construction errors with CenterColumnStudyReactor
With some arguments settings the CenterColumnStudyReactor fails to produce geometry

The following model doesn't work over here

```
import paramak            
my_reactor = paramak.CenterColumnStudyReactor(
    inner_bore_radial_thickness=50,
    inboard_tf_leg_radial_thickness=100,
    center_column_shield_radial_thickness_mid=50,
    center_column_shield_radial_thickness_upper=70,
    inboard_firstwall_radial_thickness=20,
    divertor_radial_thickness=50,
    inner_plasma_gap_radial_thickness=50,
    plasma_radial_thickness=100,
    outer_plasma_gap_radial_thickness=50,
    center_column_arc_vertical_thickness=200,
    plasma_high_point=(350, 0),
    plasma_gap_vertical_thickness=20,
    rotation_angle=360,
)
```

Perhaps this is a good time to rewrite the model so that is avoids the use of plasma_high_point which can be difficult for users to set correctly

### PR DESCRIPTION
**Pull request by Shimwell**
## Proposed changes

This fixes #338 by redesigning the submersion and study reactors to use plasma elongation and plasma triangular instead of plasma high point. This is nice as plasma high point was always tricky for users to set as it needed to be made at the correct x value (not too big and not too small).  However it is also a breaking change as the submersion reactor and the center column study reactor now accept different input arguments. Tests have bee updated accordingly

Screenshot from 2020-11-12 13-30-36

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Shimwell** [comment]
Looks like it is failing some unrelated tests

**Comment by Shimwell** [comment]
@billingsley-john does this interfere with your work on the hash of a reactor. If not then perhaps we can merge it

**Comment by billingsley-john** [comment]
> @billingsley-john does this interfere with your work on the hash of a reactor. If not then perhaps we can merge it once I've added the new documentation images

I imagine there will be some merge conflicts; not sure which order of merging is better. There are still tests failing on the reactor_hash_branch

**Comment by Shimwell** [comment]
the hash PR has been merged #459 and minor conflicts resolved on this branch

**Pull request merged**
