### PR TITLE
Fix azimuthal placement

### PR DESCRIPTION
**Pull request by billingsley-john**
## Proposed changes

PR which allows the number of inner tf coils to be controlled by the azimuth_placement_angle parameter.
if number_of_coils = value and azimuth_placement_angle = None: value number of tf coils spaced evenly over 360 degrees.
if number_of_coils = value and azimuth_placement_angle = different value: error raised. (both values must be the same).
if number_of_coils = None and azimuth_placement_angle = None: error raised. (at least one must be specified).
if number_of_coils = None and azimuth_placement_angle = value: coils placed at values specified.

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

No further comments

### CODE REVIEW

**Comment by billingsley-john** [comment]
what do you think of this solution @Shimwell ?

**Comment by billingsley-john** [comment]
ToroidalFieldCoilPrincetonD also has the same issue

**Comment by billingsley-john** [comment]
At this stage, users can change shape.number_of_coils after construction, but this does not change shape.azimuth_placement_angle because find_azimuth_placement_angle() method is only called upon initial construction. Likewise, changing shape.azimuth_placement_angle after initial construction does not change shape.number_of_coils.
Instead, find_azimuth_placement_angle() should be called upon each solid construction to ensure shape.number_of_coils and self.azimuth_placement_angle are kept up to date with each other. This justifies the use of a method rather than doing checks in the setters of each parameter as performing checks in the setter would prevent the parameters ever being changed as the parameters can only be updated one at a time, meaning an error would always be returned

**Comment by Shimwell** [comment]
Tricky stuff, can a modified hash method help here

**Pull request closed without merging**
