### PR TITLE
Add single null design

### PR DESCRIPTION
**Pull request by billingsley-john**
PR which adds a single null parametric reactor.
The reactor is based on the BallReactor, but takes an additional argument of divertor_position = ["upper", "lower"] which specifies the divertor location.
Adds examples and tests for SingleNullReactor and updates docstrings for BallReactor tests

### CODE REVIEW

**Comment by billingsley-john** [comment]
Resolves #164

**Comment by RemiTheWarrior** [comment]
@billingsley-john does this design have a X point ? it seems you're using the non-null version of the plasma object. If you want to see a sharp x point then you'd have to use `PlasmaBoundaries` object. Depends on what you want :-)

**Comment by billingsley-john** [comment]
You're right, this reactor uses the simple tokamak plasma shape. In the future, we should think about using a more complex plasma, but for now, this is just a simple adaptation of the BallReactor.

**Comment by billingsley-john** [comment]
A different method may be implemented. See #164

**Comment by billingsley-john** [comment]
This particular implementation of a single null reactor using the ball reactor is outdated, a better implementation is in #199

**Pull request closed without merging**
