### PR TITLE
Migration to Cadquery master

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
## Proposed changes

This PR makes the required changes for the paramak to be compatible with the current cadquery master.
Some bugs can only be fixed with this new version of cadquery:
- #445 
- #435 

This new Cadquery version now raises Construction Errors when attempting at building an overlapping solid (which wasn't the case in version 2).
Such solids were being created in the test suite, and in BallReactor and SingleNullBallReactor (BlanketFP).
In order to avoid overlapping of BlanketFP, this component has been modified and now ignores points with negative R coordinates:
image

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [x] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by Shimwell — APPROVED** [review]
Just what we needed

**Comment by RemDelaporteMathurin** [comment]
@Shimwell it seems that the cadquery version is not master here.. otherwise those tests would pass. Any idea ?

**Comment by Shimwell** [comment]
I have tried to add a separate part that deletes the temporary docker image.

I just tried to add a deletion for that temporary dockerhub image we are making. At this stage the whole thing is a bit messy compared to the github actions alternative.

Stages that need doing in circle CI that would not need doing in Github Actions
- upload a dockerhub image
- dowload a dockerhub image
- delete a dockerhub image

It is still an improvement on what we currently have with a static image but I would not rule out swtiching to something else in the future

**Comment by Shimwell** [comment]
Deleting the docker image is proving to be more tricky that I originally thought https://app.circleci.com/pipelines/github/ukaea/paramak/1747/workflows/ede0660d-f9fd-46d1-8028-e5c5d3626960/jobs/1848

**Comment by RemDelaporteMathurin** [comment]
Opened a ticket on Codecov discourse to try and figure out what's happening here.
https://community.codecov.io/t/permission-denied-while-uploading-coverage/2344

**Pull request merged**
