### PR TITLE
added segments maker feature

### PR DESCRIPTION
**Pull request by Shimwell**
## Proposed changes

This adds a PoloidalSegmenter component that can be used to segment up other components poloidally

Future use of this PoloidalSegmenter would be to use an intersect method together with another component to segment the component up poloidally. This is useful for neutron wall loading tallies where the number of neutrons passing through the first wall is needed as a function of poloidal angle

Screenshot from 2020-09-20 22-15-00

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [x] Documentation Update (if none of the other choices apply)
- [x] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

There is still lots to do to make this complete. 
- A utility function must be added to allow the component to be intersected with this component.
- Tests
- Example in the documentation

### CODE REVIEW

**Comment by Shimwell** [comment]
Docs, tests and examples have been updated.

The segmenter useage is as follows

Screenshot from 2020-09-21 18-38-25

**Comment by Shimwell** [comment]
@billingsley-john any chance you could take a peak at the hash part of poloidal_segmenter.py

**Comment by billingsley-john** [comment]
@Shimwell your implementation of the hash_value was fine!

**Comment by Shimwell** [comment]
Added another test which helps avoid the drop in code coverage score :-)

**Pull request merged**
