### PR TITLE
Refactoring of Shape() + pep8

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
## Proposed changes

This PR proposes small refactoring changes in Shape() as well as pep8 linting.
Garanteed zero pep8 error ✔️ 

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Shimwell** [comment]
This is all very nice. I have been meaning to update these raise ValueError things. Sometimes when they are split over two lines using the \ they can be hard to read in the terminal

What do people thing of this methods

https://github.com/openmc-dev/openmc/blob/5b81083742f871dc233dbba30332dd73ae50d3f3/openmc/material.py#L351-L354

**Comment by RemDelaporteMathurin** [comment]
> This is all very nice. I have been meaning to update these raise ValueError things. Sometimes when they are split over two lines using the \ they can be hard to read in the terminal
> 
> What do people thing of this methods
> 
> https://github.com/openmc-dev/openmc/blob/5b81083742f871dc233dbba30332dd73ae50d3f3/openmc/material.py#L351-L354

I can use this instead. Though the \ is here though

**Comment by RemDelaporteMathurin** [comment]
alright @Shimwell what do you reckon ? :-)

**Review by Shimwell — APPROVED** [review]

**Comment by Shimwell** [comment]
Great stuff again Remi

**Pull request merged**
