### PR TITLE
Fix overlapping BlanketFP

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
## Proposed changes

This PR make the BlanketFP component ignore points if the R coordinate is negative. Thus avoiding potential construction errors from occuring.

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Shimwell** [comment]
I get a small error in the geometry with these settings

```
    my_reactor = paramak.BallReactor(
        inner_bore_radial_thickness=10,
        inboard_tf_leg_radial_thickness=30,
        center_column_shield_radial_thickness=60,
        divertor_radial_thickness=50,
        inner_plasma_gap_radial_thickness=30,
        plasma_radial_thickness=300,
        outer_plasma_gap_radial_thickness=30,
        firstwall_radial_thickness=30,
        blanket_radial_thickness=50,
        blanket_rear_wall_radial_thickness=30,
        elongation=2,
        triangularity=0.55,
        number_of_tf_coils=16,
        rotation_angle=180,
        pf_coil_radial_thicknesses=[50, 50, 50, 50],
        pf_coil_vertical_thicknesses=[50, 50, 50, 50],
        pf_coil_to_rear_blanket_radial_gap=50,
        pf_coil_to_tf_coil_radial_gap=50,
        outboard_tf_coil_radial_thickness=100,
        outboard_tf_coil_poloidal_thickness=50
    )
```

Screenshot from 2020-11-16 20-05-58

**Comment by RemDelaporteMathurin** [comment]
Yeah no this fix don't work anyway. It just a coincidence when the angles are set to 180 instead of 90...

**Comment by Shimwell** [comment]
ah ok, looks like a problem for another day then

**Comment by RemDelaporteMathurin** [comment]
> ah ok, looks like a problem for another day then

The p[0] = max(p[0], 0) workaround won't work cause it can (will) cause a flat geometry on the inboard

**Comment by RemDelaporteMathurin** [comment]
@Shimwell this new approach should work now

**Review by Shimwell — APPROVED** [review]
Great stuff

**Pull request merged**
