### PR TITLE
added openmp threads option

### PR DESCRIPTION
**Pull request by billingsley-john**
## Proposed changes

PR which adds an optional openmp_threads argument to .simulate() to control the number of threads OpenMC uses during a simulation.

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by billingsley-john** [comment]
What do you think of something like this? @Shimwell @RemDelaporteMathurin

**Comment by Shimwell** [comment]
Looks fine to me, None takes all the threads which is the default

Might need to add some clear doc strings as the default of None which results in all the threads could confuse

**Comment by Shimwell** [comment]
thanks for that, docstring

any thoughts on the testing

could make use of time and check that a 2 core is faster than the 1 core. But I'm not sure if the CI has many cores available.

https://www.programiz.com/python-programming/time

perhaps just local testing is fine for this

**Comment by billingsley-john** [comment]
I shall explore some testing options to see how easy it would be. I agree, timings would be the way to about it

**Review by Shimwell — APPROVED** [review]
Looks good, tests for this are optional as there is testing in openmc for threads scaling

**Review by Shimwell — APPROVED** [review]
thanks for that change to make it the same as the openmc argument

**Pull request merged**
