### PR TITLE
Fix inboard firstwall fccs

### LINKED ISSUE #374: BUG: azimuth_placement_angle not taken into account for InboardFirstwallFCCS
**How to reproduce**
```python
import paramak

a = paramak.CenterColumnShieldFlatTopHyperbola(
    height=200,
    arc_height=100,
    inner_radius=50,
    mid_radius=80,
    outer_radius=100)

# a shape placed at 0deg
b = paramak.InboardFirstwallFCCS(
    central_column_shield=a,
    thickness=20,
    rotation_angle=180,
    azimuth_placement_angle=0)
b.export_stl("0deg.stl")

# a shape placed at the opposite (180deg)
c = paramak.InboardFirstwallFCCS(
    central_column_shield=a,
    thickness=20,
    rotation_angle=180,
    azimuth_placement_angle=180)
c.export_stl("180deg.stl")
```
**Current**
The two shapes have the same placement angle
image

**Expected**
image

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
## Proposed changes

This fixed #374.

In InboardFirstwallFCCS, instead of overwritting the create_solid method, the find_points method is overwritten.
Therefore, the boolean operations and the azimuth placement angle can be set.

2 unit tests have been added to catch the bugs.

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [x] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
@Shimwell @billingsley-john I see one issue with this : the following will overwrite the cut attribute (but that's the case for all components really). More importantly, central_column_shield won't be in the cut attribute anymore (ie. the shape won't be hollow). Perhaps something should be put in the setters/getters ?

```python
import paramak

a = paramak.CenterColumnShieldFlatTopCircular(
    height=500,
    arc_height=300,
    inner_radius=30,
    mid_radius=70,
    outer_radius=120)
b = paramak.InboardFirstwallFCCS(
    central_column_shield=a,
    thickness=20,
    rotation_angle=180,
    azimuth_placement_angle=0)

b.cut = another_shape

```

**Comment by RemDelaporteMathurin** [comment]
> @Shimwell @billingsley-john I see one issue with this : the following will overwrite the cut attribute (but that's the case for all components really). More importantly, central_column_shield won't be in the cut attribute anymore (ie. the shape won't be hollow). Perhaps something should be put in the setters/getters ?
> 
> ```python
> import paramak
> 
> a = paramak.CenterColumnShieldFlatTopCircular(
>     height=500,
>     arc_height=300,
>     inner_radius=30,
>     mid_radius=70,
>     outer_radius=120)
> b = paramak.InboardFirstwallFCCS(
>     central_column_shield=a,
>     thickness=20,
>     rotation_angle=180,
>     azimuth_placement_angle=0)
> 
> b.cut = another_shape
> ```

This has been fixed by reassigning the cut attribute in find_points method

**Comment by Shimwell** [comment]
Thanks this looks helpful Remi, happy to merge if @billingsley-john is

John and I have been meaning to update this shape for a while but never got around to it. One of the things that we wanted to do was introduce a rotation angle and an offset angle. I think this PR makes it easier. But there is a chance that we would have t bring the create_solid back in some form or another

**Comment by RemDelaporteMathurin** [comment]
> Thanks this looks helpful Remi, happy to merge if @billingsley-john is
> 
> John and I have been meaning to update this shape for a while but never got around to it. One of the things that we wanted to do was introduce a rotation angle and an offset angle. I think this PR makes it easier. But there is a chance that we would have t bring the create_solid back in some form or another

@Shimwell the rotation angle works fine here 
image

What would the offset angle be ?

**Comment by Shimwell** [comment]
ah sorry I was getting mixed up with another shape

**Pull request merged**
