### PR TITLE
removed .py script examples and replaced with .ipynb

### LINKED ISSUE #831: unexpected keyword argument 'pf_coil_to_rear_blanket_radial_gap'
Tried to run the ball_reactor.py example:

```
TypeErrorTraceback (most recent call last)
<ipython-input-3-fdead2d19fc8> in <module>
     44 
     45 if __name__ == "__main__":
---> 46     make_ball_reactor(('stp', 'neutronics', 'svg', 'stl', 'html'))

<ipython-input-3-fdead2d19fc8> in make_ball_reactor(outputs, output_folder)
      7                       output_folder='BallReactor'):
      8 
----> 9     my_reactor = paramak.BallReactor(
     10         inner_bore_radial_thickness=10,
     11         inboard_tf_leg_radial_thickness=30,

TypeError: __init__() got an unexpected keyword argument 'pf_coil_to_rear_blanket_radial_gap'
```

### PR DESCRIPTION
**Pull request by shimwell**
## Proposed changes

The py files were becoming a bit of a burden to maintain and the ipynb files were starting to duplicate them.

This PR tidies up the examples so that all the examples are on python notebooks instead of py scripts.

TODO
-[ ] update links in the documentation rst files
-[ ] convert neutroncis examples to notebooks

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
@Shimwell these notebooks will look fab! I recently learned my way through testing demos notebooks in the CI by first converting them to .py with nbconvert and then run them. If you're interested let me know

**Comment by shimwell** [comment]
> @Shimwell these notebooks will look fab! I recently learned my way through testing demos notebooks in the CI by first converting them to .py with nbconvert and then run them. If you're interested let me know

Thanks Remi, there is a method used to test the notebooks in this PR but I would be keen to take a look at anything just in case the method I have can be improved on

https://github.com/ukaea/paramak/blob/develop/tests/notebook_testing.py

**Comment by RemDelaporteMathurin** [comment]
@Shimwell this is what I use for FESTIM. It is a seperated workflow that runs in parrallel to the unit test suite.

```yml
# This is a basic workflow to help you get started with Actions

name: Test demos

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: quay.io/fenicsproject/stable:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run the notebooks
        run: |
          jupyter-nbconvert --to python demos/demo_multi_materials.ipynb
          mkdir outputs
          python3 -m demos.demo_multi_materials
          jupyter-nbconvert --to python demos/demo_meshes.ipynb
          python3 -m demos.demo_meshes
          jupyter-nbconvert --to python demos/demo_derived_quantities.ipynb
          python3 -m demos.demo_derived_quantities
          jupyter-nbconvert --to python demos/demo_Ogorodnikova.ipynb
          python3 -m demos.demo_Ogorodnikova
          jupyter-nbconvert --to python demos/demo_coupled_heat_transfer.ipynb
          python3 -m demos.demo_coupled_heat_transfer
```

**Comment by shimwell** [comment]
Screenshot from 2021-05-07 18-42-07

**Pull request merged**
