### PR TITLE
moved cut union intersect into shape

### PR DESCRIPTION
**Pull request by billingsley-john**
## Proposed changes

Code refactoring to move cut, union and intersect getter/setter pairs into shape.py and having each parametric shape inherit. This removes the need for boolean method getter/setter pairs in each parametric shape.
Ideally, the boolean commands for performing the operations should be moved out of create_solid() and into a common method in shape.py which is used in create_solid() by each parametric shape. This also allows the boolean operations to be used by Shape.

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests
- [x] Code refactoring

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

No further comments

### CODE REVIEW

**Comment by billingsley-john** [comment]
Extensive testing must be performed before this branch is merged.
Local tests should be performed and additional tests should be added to the test suite to ensure functionality is as expected.
Boolean operations need to be moved from create_solid() into shape.py

**Comment by billingsley-john** [comment]
Tests need to be re-organised and additional tests need to be added

**Comment by Shimwell** [comment]
Looks good John feel free to merge when you are happy it works.
Submersion reactor might provide a good test as it makes use of boolean opperations

**Comment by billingsley-john** [comment]
The boolean functions work as expected. However, sometimes some components of the single null ball reactor are not created successfully (but an error is not returned). However, I think this is an existing error rather than an error caused by this PR, so will merge and troubleshoot afterwards. Issue will be raised.

**Pull request merged**
