### PR TITLE
Add cooling channel ring parametric component

### PR DESCRIPTION
**Pull request by billingsley-john**
## Proposed changes

Adds straight and curved coolant channel ring parametric shapes. These would allow the incorporation of coolant channels into geometry models.

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by billingsley-john** [comment]
Screenshot from 2020-11-02 16-11-51
Screenshot from 2020-11-02 16-12-18

**Comment by Shimwell** [comment]
Would it be possible to add a svg image to this PR just so we can check the parameters make sense.

Also I noticed the stp_filename argument has been removed from a few of the parametric component examples. I think these filenames are needed for the tests to pass

**Comment by billingsley-john** [comment]
> Great to see these shapes arriving.
> 
> Would it be possible to add a svg image to this PR just so we can check the parameters make sense.
> 
> Also I noticed the stp_filename argument has been removed from a few of the parametric component examples. I think these filenames are needed for the tests to pass

Yes, the labelled svg images will be added. 
Oh I see! I wrongly assumed the test would check for the default stp_filename. I can fix this.

**Comment by billingsley-john** [comment]
coolant_channel_ring_straight
coolant_channel_ring_curved

**Comment by billingsley-john** [comment]
Screenshot from 2020-11-03 11-28-47
Screenshot from 2020-11-03 11-29-46

**Comment by billingsley-john** [comment]
straight

**Comment by billingsley-john** [comment]
See #475

**Pull request closed without merging**
