### PR TITLE
Add cooling channel ring component

### PR DESCRIPTION
**Pull request by billingsley-john**
## Proposed changes

PR to add two parametric shapes, CoolantChannelRingStraight and CoolantChannelRingCurved which allow the easy incorporation of coolant channels into geometries.

This is a new PR based on #433 

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [x] Documentation Update (if none of the other choices apply)
- [x] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

No further comments

### CODE REVIEW

**Comment by billingsley-john** [comment]
CoolantChannelRingStraight currently has issues with the azimuthal placement angle axis. This is due to other changes to the paramak and the introduction of a rotation_axis for some parametric_shapes? Swept shapes are standalone so do not have this problem, but also do not have the addition of a rotation_axis, so these could also be updated accordingly to give full flexibility when constructing swept shapes.

**Comment by Shimwell** [comment]
Any chance these shapes can be added to the rst doc files, they look too good to leave out.

**Comment by billingsley-john** [comment]
Screenshot from 2020-11-13 08-53-53
Screenshot from 2020-11-13 08-54-48

**Comment by billingsley-john** [comment]
If there's no objections @Shimwell or @RemDelaporteMathurin I will merge

**Pull request merged**
