### PR TITLE
No more error if first and last points are the same

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
## Proposed changes

In the following lines of `Shape()` it is clear that having the first and last point identical is required by the code. This PR therefore proposes to get rid of the error raise.

https://github.com/ukaea/paramak/blob/77bdc10a2744fb50062f42342f863bad94a2ba98/paramak/shape.py#L302-L307

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by billingsley-john** [comment]
I like this idea. The only problem I can see is that it would allow users to input things like:

`shape = p.RotateMixedShape(points=[(0, 0, "straight"), (0, 20, "spline"), (20, 20, "spline"), (0, 0, "spline")])`

where the connection on the first and last points are not the same. This does not cause any issues with solid construction, but could be confusing for users.

**Comment by RemDelaporteMathurin** [comment]
> I like this idea. The only problem I can see is that it would allow users to input things like:
> 
> `shape = p.RotateMixedShape(points=[(0, 0, "straight"), (0, 20, "spline"), (20, 20, "spline"), (0, 0, "spline")])`
> 
> where the connection on the first and last points are not the same. This does not cause any issues with solid construction, but could be confusing for users.

You are right. perhaps adding a warning or something ?

**Comment by Shimwell** [comment]
I think that last connection type would be ignored by the code.

Perhaps it is best to just stop the user entering in that last point

**Comment by RemDelaporteMathurin** [comment]
Perhaps just close this PR then :-)

**Comment by Shimwell** [comment]
ok lets close this but keep the branch just in case

**Pull request closed without merging**
