### PR TITLE
updated cq and python install

### PR DESCRIPTION
**Pull request by billingsley-john**
## Proposed changes

PR which fixes CadQuery and Python installation in Dockerfile

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by shimwell** [comment]
Thanks for taking a look at these docs, unfortunately I don't think that update fixed the issue as docs appear to be missing the doc-strings still

https://paramak--769.org.readthedocs.build/en/769/paramak.parametric_components.html

**Comment by billingsley-john** [comment]
Warnings module causing issues - Cannot be imported, and doesn't exist as a standalone python package. Maybe some additional sphinx-specific things have to be changed.

**Comment by billingsley-john** [comment]
Continued in #774

**Comment by shimwell** [comment]
> Warnings module causing issues - Cannot be imported, and doesn't exist as a standalone python package. Maybe some additional sphinx-specific things have to be changed.

warnings appears to import over here on python 3.8
Screenshot from 2021-03-09 22-28-43

**Pull request closed without merging**
