### PR TITLE
allowing magnets to be placed anywhere

### PR DESCRIPTION
**Pull request by shimwell**
## Proposed changes

Allows PF coils to be placed anywhere as discussed in issue #248

Three new arguments are introduced, to control the position

    pf_coil_radial_position
    pf_coil_vertical_position
    rear_blanket_to_tf_gap

TODO
- [x] tests
- [x] documentation
- [x] getters and setters to test for invalid entry
- [x] apply to submersion reactor as well
- [ ] update examples

ples

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
@Shimwell this will definitely add flexibility. It seems to be a breaking change though? Could these new arguments have default value (None) and this would produce the former behaviour?

**Comment by shimwell** [comment]
setting both to None
```
        pf_coil_radial_position: Optional[Union[float, List[float]]] = None,
        pf_coil_vertical_position: Optional[Union[float, List[float]]] = None,
```

But I think it will still be breaking as one of the gap arguments is no longer needed

**Comment by shimwell** [comment]
I still have to update the examples and reactors that inherit from BallReactor and Submersion reactor might need a few changes

**Comment by shimwell** [comment]
Updating the docs images 

SubmersionTokamak

**Comment by shimwell** [comment]
another diagram fro the docs ball_reactor(1)

**Pull request merged**
