### PR TITLE
Smaller graveyard

### PR DESCRIPTION
**Pull request by Shimwell**
## Proposed changes

The previous method of calculating the graveyard used largestDimension() for shapes while it used BoundingBox for components. This resulted in large offsets between the actual geometry and the bounding box which makes the geometry tricky to inspect with paraview. This PR implements the use of BoundingBox for both components and shapes. This makes the graveyard_offset work nicely.

before
Screenshot from 2020-11-05 19-46-29

after
Screenshot from 2020-11-05 19-45-44

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Shimwell** [comment]
This one doesn't bring in anything new but just fixes a bug. So unless there are any objections it would be good to go ahead and merge this one

**Comment by billingsley-john** [comment]
This is great. Much better than what was done previously!

**Comment by RemDelaporteMathurin** [comment]
@Shimwell I think there's one test failing due to line 425 in test_Reactor.py

**Comment by billingsley-john** [comment]
> @Shimwell I think there's one test failing due to line 425 in test_Reactor.py

I can update and merge

**Comment by Shimwell** [comment]
Just tried to fix that test, thanks for letting me know Remi. Hope that does it.

**Comment by billingsley-john** [comment]
The tests failing now are known issues

**Comment by billingsley-john** [comment]
Failing test linked to #445. Think this PR can be merged

**Pull request merged**
