### PR TITLE
Add reactor hash value

### PR DESCRIPTION
**Pull request by billingsley-john**
## Proposed changes

PR which implements a reactor_hash_value to allow the conditional reconstruction of all shapes in the reactor object. When .shapes_and_components is called, the current instance of the reactor object is compared with the stored hash value of the currently constructed reactor object. If they are different, the shapes/components are reconstructed and returned. If they are equal, the previously constructed shapes/components are returned.

The hash calculation methods for shapes and reactors have been moved to paramak/utils.py, however, could be moved back into shape.py and reactor.py in the future. Separate hash calculation methods were required for shapes and reactors to prevent looping/recalling the hash check at the reactor level when the shapes/components are constructed (and their own hash values are checked).

This PR also includes some minor changes to other scripts and the test suite which were made made as part of the debugging/testing of this branch.

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [x] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

In the future, get_hash() for shapes could be renamed to get_shape_hash() to be consistent with get_reactor_hash()

### CODE REVIEW

**Comment by billingsley-john** [comment]
Tests need to be added

**Comment by billingsley-john** [comment]
Some keys_to_ignore may not be required as we are no longer appending to .shapes_and_components. i.e. may no longer get stuck in an infinite loop of the hash_value constantly changing and re-triggering create_solids()

**Comment by billingsley-john** [comment]
Add a test showing time saving

**Comment by billingsley-john** [comment]
Perhaps the two get hash methods would be more suitable in shape.py and reactor.py to separate them

**Comment by billingsley-john** [comment]
check rotation_angle test fails which were appearing locally

**Review by Shimwell — APPROVED** [review]

**Pull request merged**
