### PR TITLE
Parametric shape refactoring

### LINKED ISSUE #346: Adding extrude both as an options
This is a nice and easy issue ideal for a first contribution 

The ExtrudeMixedShape and the ExtrudeSplineShape could do with an optional argument that allow extrusion in one or both directions.

Both directions is currently hard coded in these two classes

These two files that will need changing

https://github.com/ukaea/paramak/blob/develop/paramak/parametric_shapes/extruded_spline_shape.py
https://github.com/ukaea/paramak/blob/develop/paramak/parametric_shapes/extruded_mixed_shape.py

There are two other extrude shapes that already have this feature so might be useful (ExtrudeStraightShape and ExtrudeCirlceShape)

Here are the relevant lines from ExtrudeStraightShape that can be copied

https://github.com/ukaea/paramak/blob/12b75aa2a2bee7c589b0e3ff7fce2fd9dc0d77e8/paramak/parametric_shapes/extruded_straight_shape.py#L21
https://github.com/ukaea/paramak/blob/12b75aa2a2bee7c589b0e3ff7fce2fd9dc0d77e8/paramak/parametric_shapes/extruded_straight_shape.py#L42
https://github.com/ukaea/paramak/blob/12b75aa2a2bee7c589b0e3ff7fce2fd9dc0d77e8/paramak/parametric_shapes/extruded_straight_shape.py#L82
https://github.com/ukaea/paramak/blob/12b75aa2a2bee7c589b0e3ff7fce2fd9dc0d77e8/paramak/parametric_shapes/extruded_straight_shape.py#L105

### PR DESCRIPTION
**Pull request by Shimwell**
## Proposed changes

This is the same as the previous PR from Remi but just done on the internal branches

This PR proposes a refactoring of the parametric shapes.
Instead of having parametric shapes inherit from shape, the non-mixed shapes (eg. `ExtrudeStraightShape`, `RotateSplineShape`) now inherit from the mixed shape (eg, `ExtrudeMixedShape`, `RotateMixedShape`).

This allows to avoid code repetition (`create_solid` method).

`RotateCircleShape` and `ExtrudeCircleShape` aren't impacted by this refactoring since these classes aren't used in the same way.

Others:
- Fixes #346 #392 

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Shimwell** [comment]
Ah conflicts, I'm a bit cautious about trying to fix these as I think I might mess it up, any chance @RemDelaporteMathurin could take a look

**Comment by billingsley-john** [comment]
Is this now ready for merging @RemDelaporteMathurin?

**Comment by RemDelaporteMathurin** [comment]
Hi John, I think it is! Perhaps the sweepShape will have to be refactored a bit later as well.

**Comment by billingsley-john** [comment]
RotateSplineShape() returns a local error for me.

`test_shape = p.RotateSplineShape(points=[(0, 0), (0, 20), (20, 20), (20, 0)])
test_shape.export_stp('test.stp')`

**Comment by RemDelaporteMathurin** [comment]
What is the error ?

**Comment by billingsley-john** [comment]
BRep_API: command not done

This also seems to be happening on the main branch for me too.

**Comment by RemDelaporteMathurin** [comment]
Ah, maybe it isn't related to this refactoring then

**Comment by billingsley-john** [comment]
@RemDelaporteMathurin or @Shimwell , could you confirm whether this is also happening for you?

**Comment by RemDelaporteMathurin** [comment]
I am not able to reproduce the code, neither in main or on the parametric_shape_refactoring branch.
image

**Comment by billingsley-john** [comment]
Ah okay, it looks like a local issue for me then

**Comment by Shimwell** [comment]
Looks good from here, lets merge this

**Comment by billingsley-john** [comment]
> Looks good from here, lets merge this

Yes, happy to merge

**Pull request merged**
