### PR TITLE
Parametric shapes refactoring

### PR DESCRIPTION
**Pull request by RemiTheWarrior**
## Proposed changes

This PR aims at refactoring the parametric shapes by avoiding code repetition with solid getters & setters.
- refactoring
- In TripleArc and PrincetonD magnets, the way of including the inner leg was replaced by conditionnal construction of points reducing the code repetition

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by Shimwell** [comment]
Nice plan Remi, let us know if you are happy to have this merged

**Comment by RemiTheWarrior** [comment]
@Shimwell It is more up to you and @billingsley-john since it might not be heading the way you initially thought. I added a dummy create_solid method to Shape().

This dummy function could perhaps allow to create 2D solid and test Shape methods at the Shape level (and not at the parametric shape levels as currently done)

**Comment by RemiTheWarrior** [comment]
@Shimwell @billingsley-john  I think this is ready for your review. The coverage is slightly lower because I removed plenty of lines that were hit...

**Comment by RemiTheWarrior** [comment]
@billingsley-john I've just tried this alternative and many tests failed. 

All raising the same AttributeError:

```
self = <paramak.parametric_components.toroidal_field_coil_coat_hanger.ToroidalFieldCoilCoatHanger object at 0x7f5ee8148b90>

    @property
    def volume(self):
>       return self.solid.val().Volume()
E       AttributeError: 'NoneType' object has no attribute 'val'

paramak/shape.py:140: AttributeError
```

**Comment by Shimwell** [comment]
I think this is ready to be merged. Thanks for checking out other options. We can always change it if need in the future. But lets get this contribution merged before it gets stale

**Pull request merged**
