### PR TITLE
ITER reactor

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
## Proposed changes

This PR adds a parametric reactor nearly entirely based on paramak built in parametric components (PF coils, PrincetonD TF coils, blanket, plasma, single null divertor).

The data for the model is taken from [this paper](https://link.springer.com/chapter/10.1007/978-3-030-42913-3_26).

The outer points of the vacuum vessel are taken fom the paper whereas the inner points are computed from the outer points of the blanket and the divertor, making it a bit more generic.

**Usage**

```python
import paramak

my_reactor = paramak.ITERTokamak(rotation_angle=180)
my_reactor.export_stp()
```

image

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by shimwell** [comment]
Just wondering which figure did you get the coordinates from, I see 26.24 has some PF coil positions but not sure about the rest

**Comment by RemDelaporteMathurin** [comment]
> Just wondering which figure did you get the coordinates from, I see 26.24 has some PF coil positions but not sure about the rest

Yes it's Figure 26.24. It has PF coils, TF coils, divertor (had to tweak the parameters to make it match), blanket and VV

**Comment by shimwell** [comment]
Screenshot from 2021-03-07 17-37-02

**Comment by shimwell** [comment]
Screenshot from 2021-03-07 17-23-32

**Review by shimwell — APPROVED** [review]
This looks ready to merge, happy to merge on Tuesday if there are no objections

**Comment by RemDelaporteMathurin** [comment]
> This looks ready to merge, happy to merge on Tuesday if there are no objections

Some additionnal features could be added like a no dome version. But this can be kept for another PR

**Comment by shimwell** [comment]
Just checked with John and he is happy.

LGTM

**Pull request merged**
