### PR TITLE
Docs for cutters and vv

### PR DESCRIPTION
**Pull request by Shimwell**
## Proposed changes

Adds some docs and images for the recently added rectangular port cutters,  circular port cuters and the vacuum vessel

Also had to reorganized a few classes to get the docs building

Also moved the component test to the component test folder (recently introduced, seperate test files for seperate components)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [x] Documentation Update (if none of the other choices apply)
- [x] New tests

## Checklist

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Made images while testing the recently added shapes and added them to the docs during the process

### CODE REVIEW

**Comment by Shimwell** [comment]
Had to remove a couple of places where the code subtracted 90 from the azimuth placement angle. This was needed so that the argument can still support lists of azimuth angles

**Comment by Shimwell** [comment]
I think this one is ready to merge

That for the nice new feature @RemDelaporteMathurin hope you don't mind the minor reshuffling I've done while understanding it

Also hope the removal of the -90 on the azimuthal placement is ok

**Comment by RemDelaporteMathurin** [comment]
@Shimwell it is all fine with me ! 😄

**Comment by Shimwell** [comment]
Screenshot from 2020-10-13 10-55-54

default workplane is 'XZ' which looks like it is working.

**Comment by RemDelaporteMathurin** [comment]
Yup

I just wanted to be consistent with the rotation of the vessel which starts à 0degree (see image) but perhaps I'm mistaken
image

**Comment by Shimwell** [comment]
ah yes I am getting the same difference in rotation and azimuhal placement angles

This shows placement angles of 0, 45, 90, 180, 225 and a rotation angle of 225

I think this issue has come up before when chatting with John and we can fix this downstream

**Comment by Shimwell** [comment]
Will merge this PR and raise that angle difference as an issue to be fixed in the parametric shape classes

**Pull request merged**
