### PR TITLE
Add selective testing

### PR DESCRIPTION
**Pull request by billingsley-john**
## Proposed changes

PR which adds matrix testing to GitHub Actions to allow testing with different versions of CadQuery, depending on the branch merging.

Pull Requests to Develop - Test just using CQ2.1
Pull Requests to Main - Test using both CQ2.1 and CQ master

Also adds 'if' statement to run_tests.sh script which uses the include-neutronics true/false value to specify which tests should run in each case. This works as intended, however, true/false has not be included in the matrix testing as some non-neutronics scrips still have neutronics dependencies, causing some non-neutronics tests to fail when using the dockerfile built without the neutronics dependencies. This will be addressed in a future PR.

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [x] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by billingsley-john** [comment]
Specifying test script not working

**Comment by billingsley-john** [comment]
Perhaps the test script "run_tests.sh" is copied into the docker container; hence, it can be found. So when we're trying these new files, they aren't being copied into the container so can't be found

**Comment by billingsley-john** [comment]
Can't get different workflows to run for PRs to different branches. Only seems to like having one set of job instructions

**Comment by billingsley-john** [comment]
GitHub Actions only support one workflow per yml file. Two yml files are required to have separate workflows for PRs to main and develop.

**Comment by billingsley-john** [comment]
Action tests now run at the correct time with the correct settings. However, tests are now failing when include-neutronics=false because there are still neutronics dependencies in some scripts

**Comment by billingsley-john** [comment]
Test results are still not returned via Actions. Perhaps another job can be added which depends on the results, so if this job completes the tests have passed, and if it doesn't complete the tests haven't passed, and hopefully this returns an unsuccessful check with a red x

**Comment by billingsley-john** [comment]
This is also ready for review @Shimwell . What do you think of this?

**Comment by shimwell** [comment]
> This is also ready for review @Shimwell . What do you think of this?

Looks like a clever solution, congrats on that you found a nice approach. I see this can also do include neutronics=False at some point as well which could be handy

**Review by shimwell — APPROVED** [review]

**Comment by shimwell** [comment]
Looks great, feel free to merge if ready

**Comment by billingsley-john** [comment]
> > This is also ready for review @Shimwell . What do you think of this?
> 
> Looks like a clever solution, congrats on that you found a nice approach. I see this can also do include neutronics=False at some point as well which could be handy

Yes, that would be great to add. I've tried to outline the current problem with doing this in #777, but this can be looked into next

**Pull request merged**
