### PR TITLE
added export_h5m to shape and using openmc.source in neutronics models

### PR DESCRIPTION
**Pull request by Shimwell**
## Proposed changes

This is a bit of a rework of the previous attempt to bring neutronics testing into the paramak.

The neutronicsModelFromRactor has been refactored in another PR to require a openmc.source instead of parametric plasma source parameters. 

This has allowed us to use a point source

The old branch was failing because the parametric plasma source was failing (perhaps due to my user error).

However simplifying the problem a bit has allowed the tests to pass and the code coverage should increase

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Shimwell** [comment]
This is pretty great, the tests are passing and include neutronics simulations for the first time.

This has only been done locally todate

Nice to know the CAD is functional as well as making nice diagrams :-)

**Comment by Shimwell** [comment]
I think this PR brings the code coverage to 96% according to this circle CI report https://app.circleci.com/pipelines/github/ukaea/paramak/2051/workflows/9d46ef96-4f1f-4abe-be9e-e110a009eade/jobs/2249

But I don't see the coverage being reported by code-cov

**Comment by RemDelaporteMathurin** [comment]
> I think this PR brings the code coverage to 96% according to this circle CI report https://app.circleci.com/pipelines/github/ukaea/paramak/2051/workflows/9d46ef96-4f1f-4abe-be9e-e110a009eade/jobs/2249
> 
> But I don't see the coverage being reported by code-cov

`/bin/bash: curl: command not found`

**Comment by Shimwell** [comment]
> > I think this PR brings the code coverage to 96% according to this circle CI report https://app.circleci.com/pipelines/github/ukaea/paramak/2051/workflows/9d46ef96-4f1f-4abe-be9e-e110a009eade/jobs/2249
> > But I don't see the coverage being reported by code-cov
> 
> `/bin/bash: curl: command not found`

Ah super that is an easy fix. Funny how the box is green even when it failed. I shall fix it soin

**Comment by Shimwell** [comment]
this last commit issue fixed #600

**Comment by Shimwell** [comment]
I managed to add one more line to the tests coverage, might help the code coverage for the patch a little bit.

**Comment by Shimwell** [comment]
Also managed to remove a couple of lines from Shape.py so the patch coverage might go down because of that

**Pull request merged**
