### PR TITLE
Adding type hinting

### PR DESCRIPTION
**Pull request by Shimwell**
## Proposed changes

Adding a little bit of type hinting to a class and a few functions. Just read this guide https://realpython.com/python-type-checking/ and wanted to give it a go.

I noticed the hover-text in VS code picks up these hints however the more interesting thing for me is the consequences this could have for doc strings.

We could in theory define all the argument and return types using type hinting and have this show up in the docs using a sphinx add on https://github.com/agronholm/sphinx-autodoc-typehints

Just making this tiny PR to start the discussion :-)

When building the docs the type now appears in smaller letters and no longer has the optional tag.

# before
Screenshot from 2020-12-30 17-21-54

# After
Screenshot from 2020-12-30 17-21-42

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code refactoring
- [x] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by RemDelaporteMathurin** [comment]
@Shimwell nice stuff overall! Just a shame that the "optionnal" tag disappears it was rather useful.

**Comment by billingsley-john** [comment]
> @Shimwell nice stuff overall! Just a shame that the "optionnal" tag disappears it was rather useful.

The optional tag can be added using this type hinting - trying to figure this out now

**Comment by billingsley-john** [comment]
> > @Shimwell nice stuff overall! Just a shame that the "optionnal" tag disappears it was rather useful.
> 
> The optional tag can be added using this type hinting - trying to figure this out now

`from typing import Optional`

`param: Optional[type]`

can be added. Not optimal formatting but gets the job done.

Screenshot from 2021-01-04 09-47-20

**Comment by billingsley-john** [comment]
Also, unfortunately, it looks like the suggested way to add multiple type options to an argument is to use Union typing.

e.g.
`from typing import Union`
`param: Union[type1, type2]`

But this doesn't look very nice as Union remains as part of the docstring.

Screenshot from 2021-01-04 10-09-16

**Comment by Shimwell** [comment]
> Also, unfortunately, it looks like the suggested way to add multiple type options to an argument is to use Union typing.
> 
> e.g.
> `from typing import Union`
> `param: Union[type1, type2]`
> 
> But this doesn't look very nice as Union remains as part of the docstring.
> 
> For example:
> 
> Screenshot from 2021-01-04 10-09-16

I wonder if readthedocs does this in a nicer way

**Pull request merged**
