### PR TITLE
Add points hash value

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
## Proposed changes

For some complex components (with equation solving or optimisers), the `find_points()` method can be very expensive computationnally. This is the case for `ToroidalFieldCoilPrincetonD`, `BlanketFP` and shapes using the points attributes of these shapes.

This same computational issue for `create_solid` has been solved by checking if the instance parameters have changed and running `create_solid` only if they have changed.

This PR proposes to do the same for `find_points`. Therefore another hash value named specific to `find_points `has been added to `Shape()`.

The computational time saved can be estimated with:
```python
import paramak
import time

t = time.time()

magnet = paramak.ToroidalFieldCoilPrincetonD(100, 200, 10, 10, 1)

for i in range(10):
    magnet.inner_points
elapsed = time.time() - t
print(elapsed)
```

**Current behaviour:**
Takes 12.73 s to compute this

**New behaviour:**
Takes 1.26 s to compute this.  --> -90% 

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [ ] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Pep8 applied
- [x] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by billingsley-john** [comment]
Unfortunately, this solution breaks the conditional reconstruction of the parametric shapes. Having "_points" in keys_to_ignore means that changing the points of a shape does not cause the solid to be reconstructed. (This is not picked up in the tests because solid reconstruction is not tested explicitly for changing the points of a shape)

**Comment by RemDelaporteMathurin** [comment]
@billingsley-john another get_hash function then ?

**Comment by billingsley-john** [comment]
> @billingsley-john another get_hash function then ?

Yes, that looks like the easiest way

**Comment by RemDelaporteMathurin** [comment]
> > @billingsley-john another get_hash function then ?
> 
> Yes, that looks like the easiest way

What about making the get_hash method generic by adding a ignored_keys argument ?
```python
def get_hash(shape, ignored_keys=[]):

    hash_object = blake2b()
    shape_dict = dict(shape.__dict__)


    for key in ignored_keys:
        if key in shape_dict.keys():
            shape_dict[key] = None

    hash_object.update(str(list(shape_dict.values())).encode("utf-8"))
    value = hash_object.hexdigest()
    return value
```

**Comment by billingsley-john** [comment]
> > > @billingsley-john another get_hash function then ?
> > 
> > 
> > Yes, that looks like the easiest way
> 
> What about making the get_hash method generic by adding a ignored_keys argument ?
> 
> ```python
> def get_hash(shape, ignored_keys=[]):
> 
>     hash_object = blake2b()
>     shape_dict = dict(shape.__dict__)
> 
> 
>     for key in ignored_keys:
>         if key in shape_dict.keys():
>             shape_dict[key] = None
> 
>     hash_object.update(str(list(shape_dict.values())).encode("utf-8"))
>     value = hash_object.hexdigest()
>     return value
> ```

Yes, that could be a good option!

**Comment by RemDelaporteMathurin** [comment]
This could also be used to replace `get_hash_reactor`

**Comment by Shimwell** [comment]
I think this can be merged, those two tests were fixed elsewhere

**Comment by RemDelaporteMathurin** [comment]
> I think this can be merged, those two tests were fixed elsewhere

When running make_parametric_single_null_submersion_reactor.py the following error is raised:
```
Traceback (most recent call last):
  File "examples/example_parametric_reactors/make_parametric_single_null_submersion_reactor.py", line 44, in <module>
    main()
  File "examples/example_parametric_reactors/make_parametric_single_null_submersion_reactor.py", line 38, in main
    my_reactor.export_stp()
  File "/home/paramak/paramak/reactor.py", line 268, in export_stp
    if len(self.stp_filenames) != len(set(self.stp_filenames)):
  File "/home/paramak/paramak/reactor.py", line 47, in stp_filenames
    values.append(shape_or_componet.stp_filename)
AttributeError: 'NoneType' object has no attribute 'stp_filename'
```

Are we sure this is fixed elsewhere ?

**Pull request merged**
