### PR TITLE
added documentation for 3d mesh arguments

### LINKED ISSUE #687: mesh_tally_3D missing from docstrings
NeutronicsModel accepts an argument called mesh_tally_3D

However it not in the docstring quite yet

https://github.com/ukaea/paramak/blob/3ce4c719540a97ef21f328d4247bcb4f35b81ae5/paramak/parametric_neutronics/neutronics_model.py#L85

It behaves in a similar manner to mesh_tally_2D

### PR DESCRIPTION
**Pull request by billingsley-john**
## Proposed changes

PR which documents the arguments related to 3D mesh tallies in neutronics_model.

fixes #687 

## Types of changes

What types of changes does your code introduce to the Paramak?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring
- [x] Documentation Update (if none of the other choices apply)
- [ ] New tests

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Pep8 applied
- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Shimwell** [comment]
Looks good, perhaps bump the version number on the last digit so the pip install gets updated.

**Comment by Shimwell** [comment]
Also I noticed "mesh_tally_3d" was used in the doc string. The arg is currently "mesh_tally_3D" with an upper case. But I think you are right and perhaps we should go through and make changes to the D to make it lower case everywhere, (pep8). Perhaps grep is useful here

**Comment by billingsley-john** [comment]
> Also I noticed "mesh_tally_3d" was used in the doc string. The arg is currently "mesh_tally_3D" with an upper case. But I think you are right and perhaps we should go through and make changes to the D to make it lower case everywhere, (pep8). Perhaps grep is useful here

Ah sorry, I didn't realise it was upper case. I'm happy to change it to upper case so that it is consistent with the 2D mesh arguments

**Comment by Shimwell** [comment]
Perhaps there are some in the examples as well

e.g. 
https://github.com/ukaea/paramak/blob/3ce4c719540a97ef21f328d4247bcb4f35b81ae5/examples/example_neutronics_simulations/component_based_mesh_simulation.py#L37-L38

**Comment by Shimwell** [comment]
Looks like the tests are failed due to that Embree version number change

**Comment by Shimwell** [comment]
I have merged in the changes from the develop branch so that Embree build error should be fixed

**Review by Shimwell — APPROVED** [review]
Good to merge on :white_check_mark:

**Comment by billingsley-john** [comment]
Embree build error seems to have returned

**Comment by Shimwell** [comment]
ah sorry about that Embree error I've been tinkering and now we can simplify the build command a bit. This is great as when the Embree version has minor changes it will still find the .so file. The previous method was quite specific but Patrick made some nice improvements on double -down

changed
```-DEMBREE_DIR=/embree/lib/cmake/embree-3.12.2 ; \```
to
````-DEMBREE_DIR=/embree ; \```

**Comment by Shimwell** [comment]
2nd commit is because I forgot we have two dockerfiles (Dockerfile and DockerfileDependencies)

**Comment by Shimwell** [comment]
Note to self we will need to change the args in task 12 from the openmc workshop

**Comment by billingsley-john** [comment]
Thanks @Shimwell  for fixing this!

**Pull request merged**
